// The public build: the same manuscript with the byline showing and the
// referees' line numbers gone.
//
//   node paper/tools/arxiv.mjs           # writes and compiles both PDFs
//   node paper/tools/arxiv.mjs --emit    # writes the shells, compiles nothing
//
// Writes paper/arxiv.tex and paper/arxiv-supplemental.tex -- generated shells
// that differ from paper.tex and supplemental.tex only in their class options
// and their front matter -- then compiles them into paper/build/.
//
// Generated rather than kept as a second copy, because a second copy of a
// 250-line preamble goes stale silently and the symptom is a public PDF built
// from last month's prose. Both shells sit in paper/ so that every relative
// \input, \includegraphics and \bibliography resolves exactly as it does for
// the submission build; they are gitignored.
//
// Every substitution asserts. A paper.tex that has moved underneath this script
// stops it rather than quietly producing the wrong document -- the same rule the
// ablation patches follow in tools/lib/instrument.mjs.
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

const HERE = new URL('../', import.meta.url); // paper/
const emitOnly = process.argv.includes('--emit');
const notes = [];

/** Replace exactly once, or say what went missing. */
function sub(text, from, to, why) {
  const n = text.split(from).length - 1;
  if (n !== 1) throw new Error(`${why}: expected 1 match of ${JSON.stringify(from)}, found ${n}`);
  return text.replace(from, to);
}

/** Drop a whole line, if it is there at all. */
function dropLine(text, needle) {
  const lines = text.split('\n');
  const kept = lines.filter((l) => !l.includes(needle));
  return { text: kept.join('\n'), dropped: lines.length - kept.length };
}

const BANNER = (source) =>
  `% GENERATED by tools/arxiv.mjs from ${source} -- do not edit, and do not commit.\n` +
  `% The public, named build. Edit ${source} and re-run the script.\n`;

// ---------------------------------------------------------------- paper

let paper = readFileSync(new URL('paper.tex', HERE), 'utf8');

paper = sub(
  paper,
  '\\documentclass[acmtog, anonymous, review]{acmart}',
  '\\documentclass[acmtog, nonacm]{acmart}',
  'class options'
);

// The submission ID is the thing that stands in for a byline while the byline is
// hidden. With the byline showing it is noise, and an empty one prints a stray
// rule in the running head.
{
  const { text, dropped } = dropLine(paper, '\\acmSubmissionID{');
  if (dropped !== 1) throw new Error(`submission ID: dropped ${dropped} lines, expected 1`);
  paper = text;
}

// A placeholder ORCID is invisible under `anonymous` and a false claim without
// it: 0000-0000-0000-0000 is a well-formed iD that belongs to nobody. Better a
// preprint with no iD than a preprint with somebody else's.
if (paper.includes('\\orcid{0000-0000-0000-0000}')) {
  const { text, dropped } = dropLine(paper, '\\orcid{0000-0000-0000-0000}');
  paper = text;
  notes.push(
    `no ORCID: dropped ${dropped} placeholder \\orcid line. Register at ` +
      `https://orcid.org/register and paste the iD into paper.tex to have it appear.`
  );
}

// `nonacm` is the class's own switch for material not being published by ACM.
// It is what removes the copyright block, the ACM Reference Format entry, the
// DOI and the volume/article/date footer -- every one of which is, on a
// preprint, a claim about a publication that has not happened. Setting those
// fields empty by hand instead makes the class read them as numbers and stop.
writeFileSync(new URL('arxiv.tex', HERE), BANNER('paper.tex') + paper);

// ---------------------------------------------------------------- supplemental

let supp = readFileSync(new URL('supplemental.tex', HERE), 'utf8');

supp = sub(
  supp,
  '\\documentclass[acmtog, anonymous]{acmart}',
  '\\documentclass[acmtog, nonacm]{acmart}',
  'supplemental class options'
);

// Cross-references reach into whichever main document was built alongside, and
// for the public build that is arxiv.aux, not paper.aux. Pointing at the wrong
// one is not an error -- it silently prints every \ref as a pair of question
// marks, or worse, resolves against a stale submission build.
supp = sub(
  supp,
  '\\externaldocument{build/paper}',
  '\\externaldocument{build/arxiv}',
  'supplemental cross-references'
);

writeFileSync(new URL('arxiv-supplemental.tex', HERE), BANNER('supplemental.tex') + supp);

console.log('wrote paper/arxiv.tex and paper/arxiv-supplemental.tex');

// ---------------------------------------------------------------- compile

if (!emitOnly) {
  const run = (file, extra = []) => {
    process.stdout.write(`  tectonic ${file} ... `);
    execFileSync('tectonic', ['-X', 'compile', file, '--outdir', 'build', ...extra], {
      cwd: new URL('.', HERE).pathname,
      stdio: ['ignore', 'ignore', 'inherit'],
    });
    console.log('ok');
  };
  // The supplemental reads build/arxiv.aux, so the paper goes first and keeps
  // its intermediates.
  run('arxiv.tex', ['--keep-intermediates']);
  run('arxiv-supplemental.tex');
  console.log('wrote paper/build/arxiv.pdf and paper/build/arxiv-supplemental.pdf');
}

for (const n of notes) console.warn(`note: ${n}`);
