// Regenerate numbers.tex and the generated tables from data/.
//
// Every figure the prose quotes comes from here, so the text cannot drift from
// the experiments. Run after any experiment changes:
//
//   node paper/tools/numbers.mjs

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { ENVELOPE_TAPS, PATTERN_META } from '../../src/types/moire.ts';
import { FIELD_PRESETS } from '../../src/fields/expr.ts';

const DATA = new URL('../data/', import.meta.url);
const PAPER = new URL('../', import.meta.url);

// A missing data file is a failure, not a silent fallback: the paper claims its
// numbers are generated, so a half-generated numbers.tex must not build.
const load = (name) => {
  const url = new URL(name, DATA);
  if (!existsSync(url)) {
    throw new Error(
      `data/${name} is missing. Run the experiment that writes it (see paper/README.md) ` +
        `before regenerating numbers.tex.`
    );
  }
  return JSON.parse(readFileSync(url, 'utf8'));
};

const out = [];
const macro = (name, value) => out.push(`\\newcommand{\\${name}}{${value}}`);
const section = (title) => out.push('', `% ---- ${title}`);
const r = (v, n = 2) => Number(v).toFixed(n);
/** Percent from a fraction. */
const pc = (v, n = 1) => r(Number(v) * 100, n);
/** Thousands separators LaTeX can typeset inside math. */
const th = (v) => Math.round(Number(v)).toLocaleString('en-US').replace(/,/g, '{,}');
const minOf = (xs) => Math.min(...xs);
const maxOf = (xs) => Math.max(...xs);

out.push(
  '% GENERATED by paper/tools/numbers.mjs -- do not edit by hand.',
  '% Every number the prose quotes, in one place, so text and data cannot drift.'
);

// The Studio's own menus, so the prose cannot claim a family or a field the tool
// does not ship.
section('src/types/moire.ts : what the Studio offers');
{
  const spell = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine',
    'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen'];
  // A field is now an expression, so this counts the presets the editor starts
  // from rather than the whole of what can be written.
  macro('fieldCount', spell[FIELD_PRESETS.length]);
  // Several sentences spell the family count out in words rather than through the
  // macro, so a change here has to be read for, not silently retypeset. The
  // paper's catalog analyses these thirteen by name; anything the Studio grows
  // afterwards is later work and out of the paper's scope, so the guard names
  // the set rather than counting it -- a count would pass if one family were
  // swapped for another.
  const CATALOG = [
    'straight-lines', 'radial-lines',
    'concentric-circles', 'concentric-squares', 'concentric-triangles',
    'concentric-polygons',
    'grid-square', 'grid-hex', 'grid-triangle',
    'curve-wave', 'curve-parabola', 'curve-hyperbola', 'curve-spiral',
    // The loxodromic clock, added when the carrier classification of §3.2
    // named it as one of the two group families the catalog lacked.
    'curve-log',
  ];
  // Families the Studio has gained since the paper was written. Listing them
  // explicitly is the point: a new family must be either added to the catalog
  // and the prose, or consciously declared out of scope here.
  const BEYOND_PAPER = ['tiling-periodic'];
  const shipped = PATTERN_META.map((m) => m.id);
  const missing = CATALOG.filter((id) => !shipped.includes(id));
  const extra = shipped.filter((id) => !CATALOG.includes(id) && !BEYOND_PAPER.includes(id));
  if (missing.length || extra.length) {
    throw new Error(
      `the paper's catalog and the Studio disagree` +
        (missing.length ? `; the Studio no longer ships ${missing.join(', ')}` : '') +
        (extra.length
          ? `; the Studio ships ${extra.join(', ')}, which the prose does not count` +
            ` -- add it to the catalog and the prose, or to BEYOND_PAPER`
          : '')
    );
  }
  macro('patternCount', spell[CATALOG.length]);
  macro('envTaps', ENVELOPE_TAPS);
}

// ---------------------------------------------------------------- fringe law
section('data/fringe.json : the fringe law');
const fringe = load('fringe.json');
{
  const withRegime = fringe.scenes.filter((s) => s.regime);
  const total = withRegime.reduce((a, s) => a + s.regime.n, 0);
  const weighted =
    withRegime.reduce((a, s) => a + s.regime.mean * s.regime.n, 0) / Math.max(total, 1);
  const worstP99 = Math.max(...withRegime.map((s) => s.regime.p99));
  const light =
    withRegime.reduce((a, s) => a + s.regime.lightGap * s.regime.n, 0) / Math.max(total, 1);
  const dark =
    withRegime.reduce((a, s) => a + s.regime.darkGap * s.regime.n, 0) / Math.max(total, 1);
  macro('fringeScenes', fringe.scenes.length);
  macro('fringeSamples', total.toLocaleString('en-US').replace(/,/g, '{,}'));
  macro('fringeMeanErr', r(weighted, 4));
  macro('fringeWorstP', r(worstP99, 3));
  macro('fringeLight', r(light, 3));
  macro('fringeDark', r(dark, 3));
  macro('fringeRegime', '1/4');

  // Table.
  const rows = fringe.scenes.map((s) => {
    if (!s.regime) {
      return `\\texttt{${s.name}} & ${s.note} & --- & --- & --- & --- & --- & $0$ \\\\`;
    }
    const g = s.regime;
    return (
      `\\texttt{${s.name}} & ${s.note} & ${g.n.toLocaleString('en-US')} & ` +
      `${r(g.mean, 4)} & ${r(g.p99, 4)} & ${r(g.swing, 3)} & ` +
      `${r(g.lightGap, 3)} / ${r(g.darkGap, 3)} & ${Math.round(s.regimeShare * 100)}\\% \\\\`
    );
  });
  writeFileSync(
    new URL('tab-fringe.tex', PAPER),
    `% GENERATED by paper/tools/numbers.mjs
\\begin{table*}[t]
\\caption{\\figlead{The fringe law, measured.} Mean and $99$th-percentile absolute
error between the one-period directional mean of the rendered ink and $\\Phi(D)$ of
Eq.~\\ref{eq:phi}, over samples in the fringe regime $\\het\\le1/4$. \\emph{Swing} is
the range of measured coverage, so it says how much fringe there was to get wrong.
\\emph{Light\\,/\\,dark} are the mean distances of the measured lightest and darkest
deciles from the nearest integer index difference; the ideals are $0$ (light
fringes at $D\\in\\Z$) and $0.5$ (dark fringes at $D\\in\\Z+\\tfrac12$). Where the
profile plateaus (low swing), the darkest decile spreads across the flat top and
its mean falls short of $0.5$ by construction. \\emph{In regime} is the share of admissible samples with $\\het\\le1/4$. The
last row has none: with those settings no fringe exists, and the criterion says so
without rendering.}
\\label{tab:fringe}
% The Families column carries long prose; \\small leaves the widest row 11pt
% over the full text width, which prints into the margin.
\\footnotesize
\\centering
\\begin{tabular}{@{}llrrrrcr@{}}
\\toprule
Scene & Families & $n$ & mean & p99 & swing & light\\,/\\,dark & in regime \\\\
\\midrule
${rows.join('\n')}
\\bottomrule
\\end{tabular}
\\end{table*}
`
  );
  console.log(`fringe: ${total} in-regime samples, weighted mean err ${r(weighted, 5)}`);
}

// --------------------------------------------------- the law across the catalog
section('data/lawatlas.json : admitted fraction per panel');
const atlas = load('lawatlas.json');
{
  const share = (slug) => {
    const hit = atlas.scenes.find((s) => s.scene === slug);
    if (!hit) throw new Error(`lawatlas.json has no scene ${slug}`);
    return pc(hit.admitted);
  };
  macro('atlasCombs', share('parallel-rotate'));
  macro('atlasCircleLines', share('circle-parallel'));
  macro('atlasHex', share('hexagon-hexagon'));
  macro('atlasCircles', share('circle-circle'));
  macro('atlasControl', share('hyperbola-parallel'));
  console.log(`law atlas: ${atlas.scenes.map((s) => `${s.scene} ${pc(s.admitted)}%`).join(', ')}`);
}

// ------------------------------------------------------------- gradient bug
section('data/gradient.json : the missing gradient divide');
const grad = load('gradient.json');
{
  const of = (name) => grad.families.find((f) => f.family === name);
  macro('gradWorstWave', r(of('Wave').worstFactor, 1));
  macro('gradWorstHyp', r(of('Hyperbola').worstFactor, 1));
  macro('gradWorstSpiral', r(of('Spiral').worstFactor, 1));
  macro('gradWorstParab', Math.round(of('Parabola').worstFactor));
  macro('gradWaveFrame', Math.round(of('Wave').meanFractionOff * 100));
  macro('gradHypFrame', Math.round(of('Hyperbola').meanFractionOff * 100));
  macro('gradParabFrame', Math.round(of('Parabola').meanFractionOff * 100));
  macro('gradSpiralFrame', Math.round(of('Spiral').meanFractionOff * 100));

  const rows = grad.families.map(
    (f) =>
      `${f.family} & ${f.dividesByGradient ? 'yes' : '\\textbf{no}'} & ${f.settings} & ` +
      `${r(f.worstFactor, 1)}$\\times$ & ${Math.round(f.meanFractionOff * 100)}\\% \\\\`
  );
  writeFileSync(
    new URL('tab-gradient.tex', PAPER),
    `% GENERATED by paper/tools/numbers.mjs
\\begin{table}[t]
\\caption{\\figlead{How wrong an undivided phase residual is.} For each curve
family, whether the shipped shader divided by $\\lVert\\nabla\\ph\\rVert$, how many
settings of that family's own sliders we swept, the worst
$\\lVert\\nabla\\ph\\rVert$ found on a $1400\\times880$ frame---which is exactly
the factor by which the stroke was too thin---and the share of the frame where
the stroke was off by more than $10\\%$. The parabola was correct all along; the
other three were not.}
\\label{tab:gradient}
\\small
\\begin{tabular}{@{}lrrrr@{}}
\\toprule
Family & divides & settings & worst factor & frame off $>10\\%$ \\\\
\\midrule
${rows.join('\n')}
\\bottomrule
\\end{tabular}
\\end{table}
`
  );
  console.log(`gradient: worst wave ${of('Wave').worstFactor}x, hyperbola ${of('Hyperbola').worstFactor}x`);
}

// -------------------------------------------------------------------- solver
// GPU pass times. The table is a curated subset of the harness's scenes -- one
// row per interesting regime rather than all 24 -- so the selection lives here,
// beside the labels, and the numbers come from the data.
section('data/gpu.json : 1200x800 = 0.96 Mpixel, one full-screen layer');
const gpu = load('gpu.json');
{
  const t = (key) => {
    const row = gpu.timings[key];
    if (!row) throw new Error(`gpu.json has no timing for "${key}"`);
    return row;
  };
  const ms = (key, solver) => t(key).solvers?.[solver]?.passMs ?? t(key)[solver].passMs;

  // label, zoom, key, and whether the row counts towards the rotated speed-up
  const GPU_ROWS = [
    ['Circle, rotation + offset', '1', 'circle rot+off @1', true],
    ['Circle, rotation + offset', '0.15', 'circle rot+off @0.15', true],
    ['Square, rotation', '1', 'square rot @1', true],
    ['Square, rotation + offset', '0.15', 'square rot+off @0.15', true],
    ['Square, offset only', '1', 'square off @1', false],
    ['Triangle, rotation', '1', 'triangle rot @1', true],
    ['Triangle, rotation', '0.15', 'triangle rot @0.15', true],
    ['Triangle, rotation + offset', '1', 'triangle rot+off @1', true],
    ['Triangle, rotation + offset', '0.15', 'triangle rot+off @0.15', true],
    ['Hexagon, rotation + offset', '0.15', 'hexagon rot+off @0.15', true],
    ['Nonagon, rotation + offset', '0.15', 'nonagon rot+off @0.15', true],
  ];
  const GPU_HARD = [
    ['Offset near spacing', '1', 'hard: off near spacing @1'],
    ['Offset near spacing', '0.15', 'hard: off near spacing @0.15'],
    ['Marginal drift $m=s$, rotated', '1', 'hard: marginal drift @1'],
  ];

  const speedups = GPU_ROWS.filter(([, , , counts]) => counts).map(
    ([, , key]) => ms(key, 'sweep') / ms(key, 'final')
  );
  macro('gpuSpeedLo', Math.round(minOf(speedups)));
  macro('gpuSpeedHi', Math.round(maxOf(speedups)));
  macro('gpuTriRotOne', r(ms('triangle rot @1', 'sweep'), 1));
  macro('gpuTriRotOneNew', r(ms('triangle rot @1', 'final'), 2));
  macro('gpuTriRotOffOut', r(ms('triangle rot+off @0.15', 'sweep'), 1));
  macro('gpuTriRotOffOutNew', r(ms('triangle rot+off @0.15', 'final'), 2));
  macro('gpuSquareOld', r(ms('square off @1', 'sweep'), 2));
  macro('gpuSquareClosed', r(ms('square off @1', 'final'), 2));
  macro('gpuSquareClosedGain', r(ms('square off @1', 'sweep') / ms('square off @1', 'final'), 1));
  // The speed-ups below are quoted in the abstract, so a contaminated measurement
  // reaches further here than anywhere else in the paper. Older gpu.json files
  // carry a single pass per cell and no stability figure at all; say so rather
  // than quoting them silently.
  if (gpu.worstSecondOverMin === undefined) {
    console.warn(
      '  WARNING: gpu.json predates the repeated timings in tools/gpu/run.mjs -- one ' +
        'pass per cell, with no check that anything else was using the GPU. The ' +
        'abstract quotes speed-ups derived from it. Re-run tools/gpu/run.mjs.'
    );
  } else if (gpu.worstSecondOverMin > 0.15) {
    throw new Error(
      `gpu.json: in some cell the second fastest pass sat ${pc(gpu.worstSecondOverMin)}% above ` +
        `the fastest, so the minimum may be one lucky scheduling window. The abstract ` +
        `quotes speed-ups from these numbers. Re-run tools/gpu/run.mjs with nothing ` +
        `else using the GPU.`
    );
  }
  // How the timing is actually taken, so 8.1 cannot describe a harness that is not
  // the one that ran. Read from the data where it records them; the fallbacks are
  // probe.mjs's own defaults, and the warning fires if a file predates recording.
  if (gpu.timingReps === undefined || gpu.timingWarm === undefined) {
    console.warn(
      '  note: gpu.json does not record reps/warm; using probe.mjs defaults (24, 4) for the protocol text.'
    );
  }
  macro('gpuReps', gpu.timingReps ?? 24);
  macro('gpuWarm', gpu.timingWarm ?? 4);
  macro('gpuPasses', gpu.timingPasses ?? 1);
  macro('gpuAdapter', gpu.meta.adapter.architecture);

  const cell = (v) => `$${r(v, 2)}$`;
  const row = ([label, zoom, key]) =>
    `    ${label} & $${zoom}$ & ${cell(ms(key, 'sweep'))} & ${cell(ms(key, 'window1'))} & ` +
    `$\\mathbf{${r(ms(key, 'final'), 2)}}$ \\\\`;
  writeFileSync(
    new URL('tab-gpu.tex', PAPER),
    `% GENERATED by paper/tools/numbers.mjs
\\begin{table}[t]
  \\centering
  \\small
  \\caption{GPU pass time in milliseconds per megapixel of solver work, one
  full-screen family, Apple \\texttt{${gpu.meta.adapter.architecture}}. \\emph{Zoom} $0.15$ is a $6.7\\times$
  zoom-out, where the index interval is widest. The last three rows are the hard
  cases of Section~\\ref{sec:limits}: an offset close to the spacing, and the
  marginal drift $m=s$ itself. Bold marks the shipped method, not the row minimum:
  where $\\rad(-\\delta)=\\lVert\\delta\\rVert$ (circles; zero offset) the two
  intervals coincide and \\loose{} saves only the constant's cost, on the nonagon
  row it is faster outright, and it loses ink globally
  (Table~\\ref{tab:fidelity}).}
  \\label{tab:gpu}
  \\begin{tabular}{llrrr}
    \\toprule
    Family & Zoom & \\sweep{} & \\loose{} & \\ours{} \\\\
    \\midrule
${GPU_ROWS.map(row).join('\n')}
    \\midrule
${GPU_HARD.map(row).join('\n')}
    \\bottomrule
  \\end{tabular}
\\end{table}
`
  );
  console.log(
    `gpu: rotated speed-up ${r(minOf(speedups), 1)}--${r(maxOf(speedups), 1)}x over sweep`
  );
}

// ---------------------------------------------------------------- the compiler
// Interpreting a field expression per pixel against unrolling it into the shader.
// Both generations run in the same kernel over the same bindings, and the timing
// floor matters as much as the numbers: the unrolled programs all land on it, so
// what is reported for them is a bound and not a value.
section('data/gpu.json : interpreting a field expression against unrolling it');
{
  const fc = gpu.fieldCost;
  if (!fc) throw new Error('gpu.json has no fieldCost block; re-run tools/gpu/run.mjs');
  const rows = Object.entries(fc.presets);
  // Milliseconds per megapixel for one evaluation, so the number does not depend
  // on the grid the probe happened to use. See `timeFieldExpr`.
  const cost = (t) => t.msPerMegapixel;
  const interp = rows.map(([, v]) => cost(v.interp));
  const unrolled = rows.map(([, v]) => cost(v.unrolled));
  const ops = rows.map(([, v]) => v.ops);
  const stmts = rows.map(([, v]) => v.statements);
  // Slope of a line through the origin: the interpreter's cost is per instruction.
  const slope =
    rows.reduce((a, [, v]) => a + v.ops * cost(v.interp), 0) /
    rows.reduce((a, [, v]) => a + v.ops * v.ops, 0);
  // A kernel with no field call at all. Nothing below this has been measured.
  const empty = cost(fc.baseline);
  const gains = rows.map(([, v]) => cost(v.interp) / cost(v.unrolled));

  macro('interpPerOp', r(slope, 3));
  macro('interpLo', r(minOf(interp), 2));
  macro('interpHi', r(maxOf(interp), 1));
  macro('interpHiOps', maxOf(ops));
  macro('unrolledLo', r(minOf(unrolled), 4));
  macro('unrolledCeil', r(maxOf(unrolled), 3));
  macro('fieldBaseline', r(empty, 4));
  macro('fieldEmptyCost', r(cost(fc.empty.interp), 3));
  macro('fieldEmptyGain', Math.round(cost(fc.empty.interp) / empty));
  macro('fieldOpsLo', minOf(ops));
  macro('fieldOpsHi', maxOf(ops));
  macro('fieldStmtHi', maxOf(stmts));
  // Agreement is a handful of f32 epsilons, so it wants scientific notation
  // rather than a run of zeros.
  const sci = (v) => {
    const [m, e] = v.toExponential(0).split('e');
    return `${m}{\\times}10^{${Number(e)}}`;
  };
  const twin = maxOf(rows.map(([, v]) => v.worst.between));
  macro('fieldTwinWorst', sci(twin));
  macro('fieldGainLo', Math.round(minOf(gains)));
  macro('fieldGainHi', Math.round(maxOf(gains)));

  const cell = (v) => `$${r(v, 3)}$`;
  writeFileSync(
    new URL('tab-compile.tex', PAPER),
    `% GENERATED by paper/tools/numbers.mjs
\\begin{table}[t]
  \\centering
  \\small
  \\caption{Cost of one field evaluation per pixel, in milliseconds per megapixel
  on an Apple \\texttt{${gpu.meta.adapter.architecture}}. \\emph{Interpreted} walks the
  bytecode from a uniform buffer; \\emph{unrolled} is that same program compiled to
  straight-line code by \\texttt{fields\\pslash emit.ts}. Both run in one kernel over
  one set of bindings and are checked against the CPU evaluator at the same points
  before either is timed; they agree with each other to
  $${sci(twin)}$ relative. Each thread evaluates
  the field $${fc.evalsPerPixel}$ times and stores once, so what is timed is the
  arithmetic rather than the store. Interpreted cost is linear in program length;
  compiled cost is not, and \\textsc{saddle} compiled is cheaper than the
  $${r(empty, 4)}$ a kernel with no field call at all costs, which is to say it has
  disappeared into the noise.}
  \\label{tab:compile}
  \\begin{tabular}{@{}lrrrrr@{}}
    \\toprule
    Preset & Instr. & Stmts & Interpreted & Unrolled & Ratio \\\\
    \\midrule
${rows
  .map(
    ([id, v]) =>
      `    \\textsc{${id}} & $${v.ops}$ & $${v.statements}$ & ${cell(cost(v.interp))} & ` +
      `$\\mathbf{${r(cost(v.unrolled), 4)}}$ & $${Math.round(cost(v.interp) / cost(v.unrolled))}\\times$ \\\\`
  )
  .join('\n')}
    \\midrule
    empty program & $0$ & $0$ & ${cell(cost(fc.empty.interp))} & $0$ & --- \\\\
    no field call & --- & --- & \\multicolumn{2}{c}{$${r(empty, 4)}$} & --- \\\\
    \\bottomrule
  \\end{tabular}
\\end{table}
`
  );
  console.log(
    `compile: interpreted ${r(slope, 3)} ms/Mpx per instruction, ` +
      `${r(minOf(interp), 3)}--${r(maxOf(interp), 2)} ms/Mpx over the presets; ` +
      `unrolled ${r(minOf(unrolled), 4)}--${r(maxOf(unrolled), 4)}, ` +
      `${Math.round(minOf(gains))}--${Math.round(maxOf(gains))}x; ` +
      `no field call ${r(empty, 4)}; empty program interpreted ${r(cost(fc.empty.interp), 3)}`
  );
}

section('data/cost.json : CPU metric evaluations per pixel, mean');
const cost = load('cost.json');
{
  // Short labels for the table, in the order the scenes should read.
  const COST_ROWS = [
    ['rot-tri', 'Triangle, rotation'],
    ['rot-hex-out', 'Hexagon, rotation, zoomed out'],
    ['off-tri', 'Triangle, translation'],
    ['off-large', 'Triangle, offset $=$ spacing'],
    ['rot-off-sq', 'Square, rotation + translation'],
    ['deep', 'Deep zoom-out, small rotation'],
    ['interference', 'Two circle families, interfering'],
  ];
  const at = (slug, solver) => {
    const scene = cost[slug];
    if (!scene) throw new Error(`cost.json has no scene "${slug}"`);
    return scene.solvers[solver];
  };
  const refs = COST_ROWS.map(([s]) => at(s, 'reference').mean);
  const sweeps = COST_ROWS.map(([s]) => at(s, 'sweep').mean);
  const ours = COST_ROWS.map(([s]) => at(s, 'final').mean);
  macro('costScenes', COST_ROWS.length);
  macro('costSweepLo', Math.round(minOf(sweeps)));
  macro('costSweepHi', Math.round(maxOf(sweeps)));
  macro('costOursLo', r(minOf(ours), 1));
  macro('costOursHi', r(maxOf(ours), 1));
  const vsSweep = COST_ROWS.map((_, i) => sweeps[i] / ours[i]);
  const vsRef = COST_ROWS.map((_, i) => refs[i] / ours[i]);
  macro('costVsSweepLo', Math.round(minOf(vsSweep)));
  macro('costVsSweepHi', Math.round(maxOf(vsSweep)));
  macro('costVsRefLo', r(minOf(vsRef), 1));
  macro('costVsRefHi', r(maxOf(vsRef), 1));

  // Bold our column except where a scene has no rotation to exploit.
  const rows = COST_ROWS.map(([slug, label]) => {
    const o = r(at(slug, 'final').mean, 1);
    const best = minOf(ours) === at(slug, 'final').mean;
    return (
      `    ${label} & $${r(at(slug, 'reference').mean, 1)}$ & $${r(at(slug, 'sweep').mean, 1)}$ & ` +
      `$${best ? `\\mathbf{${o}}` : o}$ & $${pc(at(slug, 'final').diff.fractionDiffering)}\\%$ \\\\`
    );
  });
  writeFileSync(
    new URL('tab-cost.tex', PAPER),
    `% GENERATED by paper/tools/numbers.mjs
\\begin{table}[t]
  \\centering
  \\small
  \\caption{Mean evaluations of $\\rad$ per pixel, CPU rasterizer, and fraction of
  pixels differing from \\textsc{Reference} by more than $8/255$. \\ours{} agrees
  with brute force to within that tolerance at every pixel of all ${COST_ROWS.length} scenes
  while doing less work than the exhaustive scan that defines the reference.}
  \\label{tab:cost}
  \\begin{tabular}{@{}lrrrr@{}}
    \\toprule
    & \\multicolumn{3}{c}{evaluations / pixel} & \\ours{} \\\\
    \\cmidrule(lr){2-4}
    Scene & \\textsc{Ref.} & \\sweep{} & \\ours{} & differ \\\\
    \\midrule
${rows.join('\n')}
    \\bottomrule
  \\end{tabular}
\\end{table}
`
  );
  console.log(
    `cost: ours ${r(minOf(ours), 1)}--${r(maxOf(ours), 1)} ev/px, ` +
      `${Math.round(minOf(vsSweep))}--${Math.round(maxOf(vsSweep))}x under sweep`
  );
}

section('data/artifacts.json');
const art = load('artifacts.json');
{
  const s = (scene, solver) => {
    const row = art[scene]?.solvers?.[solver];
    if (!row) throw new Error(`artifacts.json has no ${scene}/${solver}`);
    return row;
  };
  macro('artHolesSweepDiff', pc(s('holes', 'sweep').diff.fractionDiffering));
  macro('artHolesSweepEv', s('holes', 'sweep').evalsPerPixel);
  macro('artHolesOursEv', s('holes', 'final').evalsPerPixel);
  macro(
    'artHolesSaving',
    Math.round(s('holes', 'sweep').evalsPerPixel / s('holes', 'final').evalsPerPixel)
  );
  macro('artDriftLooseDiff', pc(s('drift', 'window1').diff.fractionDiffering));
  macro('artDriftRefInk', r(s('drift', 'reference').ink, 3));
  macro('artDriftLooseInk', r(s('drift', 'window1').ink, 3));
  macro('artAnchorEv', s('anchor', 'lattice-anchored').evalsPerPixel);
  macro('artAnchorRefInk', r(s('anchor', 'reference').ink, 3));
  macro('artAnchorLatticeInk', r(s('anchor', 'lattice-anchored').ink, 3));
  macro('artAnchorPixelInk', r(s('anchor', 'pixel-anchored').ink, 3));
  // The locator box Figure~\ref{fig:holes} draws over its wide panels, as
  // fractions of the image with the origin at bottom left, so the drawn window
  // is the window worstWindow() actually chose.
  {
    const b = art.holes.inset;
    const [w, h] = art.holes.size;
    macro('artHolesBoxL', r(b.x / w, 4));
    macro('artHolesBoxR', r((b.x + b.w) / w, 4));
    macro('artHolesBoxB', r(1 - (b.y + b.h) / h, 4));
    macro('artHolesBoxT', r(1 - b.y / h, 4));
  }
}

section('data/fidelity.json : the sweep against the exhaustive reference');
const fid = load('fidelity.json');
{
  const g = (solver) => {
    const row = fid.summary[solver];
    if (!row) throw new Error(`fidelity.json has no summary for "${solver}"`);
    return row;
  };
  macro('fidSettings', th(g('final').settings));
  macro('fidLegible', th(g('final').legibleSettings));
  macro('fidSweepHoles', g('sweep').settingsWithHoles);
  macro('fidSweepWorst', pc(g('sweep').worstDropped));
  macro('fidSweepLegibleHoles', g('sweep').legibleWithHoles);
  macro('fidSweepLegibleWorst', pc(g('sweep').legibleWorstDropped));
  macro('fidSweepEnvelopeHoles', g('sweep').envelopeWithHoles);
  macro('fidSweepEnvelopeWorst', pc(g('sweep').envelopeWorstDropped));
  macro('fidLooseHoles', g('window1').settingsWithHoles);
  macro('fidLooseWorst', pc(g('window1').worstDropped));
  macro('fidLooseEnvelopeHoles', g('window1').envelopeWithHoles);
  macro('fidOursHoles', g('final').settingsWithHoles);
  macro('fidOursWorst', pc(g('final').worstDropped));
}

section('data/saturation.json : the interval-width sweep');
const sat = load('saturation.json');
{
  // The figure's last bin. Quoted so the caption can name it rather than leaving
  // the one visible anomaly in the plot to be read as noise.
  const cap = sat.cap;
  if (!cap) throw new Error('saturation.json has no cap block; re-run tools/exp/saturation.mjs');
  macro('satCapSettings', th(cap.settings));
  macro('satCapMedianInk', r(cap.medianInk, 2));
  macro('satCapMinInk', r(cap.minInk, 2));
  macro('satCapNearMarginal', th(cap.nearMarginal));
  macro('satCapDriftLo', r(cap.driftRatioRange[0], 2));
  macro('satCapDriftHi', r(cap.driftRatioRange[1], 2));
  macro('satCapSpan', '2^{16}');
}
{
  macro('satSettings', th(sat.settings));
  macro('satFitting', th(sat.fitting));
  macro('satFittingPct', Math.round((sat.fitting / sat.settings) * 100));
  macro('satStrided', th(sat.strided));
  macro('satWidestFitting', sat.worstFittingSpan);
  macro('satMedianInk', r(sat.medianInkWhenStrided, 2));
  macro('satStridedLegible', th(sat.strideBelowHalfInk));
  macro('satStridedLegiblePct', pc(sat.strideBelowHalfInk / sat.settings));
  macro('satBudget', th(sat.budget));
  macro('satDriftRatioHi', r(sat.driftRatioRangeWhenStrided[1], 1));
}

section('data/degenerate.json : strided band against a deep scan');
const deg = load('degenerate.json');
{
  const d = deg.summary;
  macro('degChecked', d.settingsChecked);
  macro('degWithDrop', d.withAnyDrop);
  macro('degWorst', pc(d.worstDropped));
  macro('degMean', pc(d.meanDropped));
  macro('degLegible', d.legibleSettings);
  macro('degLegibleWorst', pc(d.legibleWorstDropped));
}

section('data/residual.json : the worked pixel of the window figure');
const res = load('residual.json');
{
  macro('figNaive', res.naiveIndex);
  macro('figTrue', res.trueIndex);
  macro('figGap', Math.abs(res.naiveIndex - res.trueIndex));
  macro('figLo', res.window.lo);
  macro('figHi', res.window.hi);
  macro('figSpan', res.span);
  macro('figEvals', res.evaluated);
  macro('figGuard', r(res.guard, 1));
  macro('figSpacing', res.spacing);
}

section('data/window.json : the interval checked against a brute-force argmin');
const win = load('window.json');
{
  macro('winChecks', th(win.checks));
  macro('winViolations', win.violations);
}

section('data/ablation.json : one mechanism removed, time relative to full');
const abl = load('ablation.json');
{
  const COLS = [
    ['tri.', 'triangle rot+off @1'],
    ['hex.\\ out', 'hexagon rot+off @0.15'],
    ['near $s$', 'square rot+off, offset near spacing @1'],
    ['marginal', 'triangle translated, marginal drift @1'],
  ];
  const ROWS = [
    ['Lipschitz skip (\\S\\ref{sec:skip})', 'no Lipschitz skip'],
    ['Support fast paths (\\S\\ref{sec:walking})', 'no support fast path'],
    ['Exact drift (\\S\\ref{sec:drift})', 'loose drift bound'],
    ['Polygon closed form (\\S\\ref{sec:closed})', 'no polygon closed form'],
    ['Carried rotation (\\S\\ref{sec:skip})', 'no carried rotation'],
    ['Accept early exit (\\S\\ref{sec:guard})', 'no accept exit'],
  ];
  const rel = (sceneKey, mech) => {
    const scene = abl[sceneKey];
    if (!scene) throw new Error(`ablation.json has no scene "${sceneKey}"`);
    if (!scene[mech]) throw new Error(`ablation.json has no "${mech}" for "${sceneKey}"`);
    // A patch that no longer matches the source records an error rather than a
    // time. Publishing around it would quietly drop a row from the table.
    if (scene[mech].error) {
      throw new Error(
        `ablation.json: "${mech}" on "${sceneKey}" did not run: ${scene[mech].error}. ` +
          `Re-run paper/tools/gpu/ablation.mjs after repairing the patch.`
      );
    }
    // Prefer the paired ratio when the data carries one: each of its repeats has
    // its own baseline measured beside it, so it is free of the drift that a
    // quotient of two separately reduced times would inherit.
    return scene[mech].ratio ?? scene[mech].passMs / scene.full.passMs;
  };

  // Two things this table cannot be trusted without, both learned the hard way.
  // Table 3 and Table 6 are both GPU measurements, and Section 8.1 names a single
  // adapter for both. If they come from different machines that sentence is wrong
  // about one of them, and the two tables cannot be read against each other.
  if (abl.device?.adapter && gpu.meta?.adapter) {
    const same =
      abl.device.adapter.vendor === gpu.meta.adapter.vendor &&
      abl.device.adapter.architecture === gpu.meta.adapter.architecture;
    if (!same) {
      throw new Error(
        `ablation.json was measured on ${abl.device.adapter.vendor}/${abl.device.adapter.architecture} ` +
          `but gpu.json on ${gpu.meta.adapter.vendor}/${gpu.meta.adapter.architecture}. ` +
          `\u00a78.1 names one adapter for both tables. Re-run tools/gpu/run.mjs and ` +
          `tools/gpu/ablation.mjs on the same machine.`
      );
    }
  }

  if (abl.worstSecondOverMin === undefined) {
    console.warn(
      '  WARNING: ablation.json predates the current tools/gpu/ablation.mjs and ' +
        'carries no floor check. Re-run tools/gpu/ablation.mjs.'
    );
  } else if (abl.worstSecondOverMin > 0.15) {
    // Every cell is a quotient of two floors, each the fastest of several passes,
    // since contention only ever adds time. This asks whether those fastest passes
    // were flukes: if a second pass reached the same floor, the floor is the
    // machine's and not an accident of scheduling.
    throw new Error(
      `ablation.json: some floor was reached only once -- the second-fastest pass ` +
        `was ${pc(abl.worstSecondOverMin)}% above it. Re-run tools/gpu/ablation.mjs ` +
        `with nothing else using the GPU.`
    );
  }
  // Two decimals reads well below 10; a 90x entry does not need them.
  const fmt = (v) => (v >= 10 ? r(v, 1) : r(v, 2));

  const skip = COLS.map(([, key]) => rel(key, 'no Lipschitz skip')).filter((v) => v > 1.001);
  macro('ablSkipLo', r(minOf(skip), 1));
  macro('ablSkipHi', r(maxOf(skip), 1));
  macro('ablClosedMarginal', fmt(rel('triangle translated, marginal drift @1', 'no polygon closed form')));
  const cheaper = ['no carried rotation', 'no accept exit']
    .flatMap((m) => COLS.map(([, key]) => rel(key, m)))
    .filter((v) => v < 0.999);
  macro('ablCostLo', Math.round((1 - maxOf(cheaper)) * 100));
  macro('ablCostHi', Math.round((1 - minOf(cheaper)) * 100));
  macro('ablMpixel', r(abl.megapixels, 2));

  const rows = ROWS.map(([label, mech]) => {
    const vals = COLS.map(([, key]) => rel(key, mech));
    const worst = maxOf(vals);
    return (
      `    ${label} & ` +
      vals
        .map((v) => (v === worst && worst >= 10 ? `$\\mathbf{${fmt(v)}}$` : `$${fmt(v)}$`))
        .join(' & ') +
      ' \\\\'
    );
  });
  writeFileSync(
    new URL('tab-ablation.tex', PAPER),
    `% GENERATED by paper/tools/numbers.mjs
\\begin{table}[t]
  \\centering
  \\small
  \\caption{Time relative to the full method when one mechanism is removed
  ($${r(abl.megapixels, 2)}$\\,Mpixel of solver work). Each column is a different family, chosen so
  that every mechanism has a column where it binds. Values below $1$ mean the
  mechanism costs time in that setting, which is the price of exactness
  elsewhere.}
  \\label{tab:ablation}
  \\begin{tabular}{lcccc}
    \\toprule
     & \\multicolumn{2}{c}{rotated} & \\multicolumn{2}{c}{translated} \\\\
    \\cmidrule(lr){2-3}\\cmidrule(lr){4-5}
    Mechanism removed & ${COLS.map(([l]) => l).join(' & ')} \\\\
    \\midrule
${rows.join('\n')}
    \\bottomrule
  \\end{tabular}
\\end{table}
`
  );
}

section('data/zoom.json : zoom stability');
const zoom = load('zoom.json');
{
  const coarse = (k) => zoom[k].perZoom[zoom[k].perZoom.length - 1];
  macro('zoomDecades', zoom.decades);
  macro('zoomRefSamples', zoom.referenceSamples);
  macro('zoomCoarsestPeriod', r(coarse('ours').periodPx, 1));
  macro('zoomFloorNoise', r(zoom.ours.worstNoise, 3));
  macro('zoomNoFloorNoise', r(zoom.noFloor.worstNoise, 3));
  macro('zoomValueNoise', r(zoom.value.worstNoise, 3));
  macro('zoomFloorNoiseCoarse', r(coarse('ours').noise, 4));
  macro('zoomNoFloorNoiseCoarse', r(coarse('noFloor').noise, 3));
  macro('zoomNoiseRatio', Math.round(coarse('noFloor').noise / Math.max(coarse('ours').noise, 1e-9)));
  macro('zoomFloorInkGain', r(zoom.worstFloorInkGain, 2));
  macro('zoomValueBias', r(Math.abs(zoom.value.worstBias), 3));
  console.log(
    `zoom: floor cuts coarse-zoom ink noise ${r(coarse('noFloor').noise, 3)} -> ` +
      `${r(coarse('ours').noise, 3)}, at up to ${r(zoom.worstFloorInkGain, 2)} extra ink`
  );
}

section('data/vector.json : against explicit geometry');
const vector = load('vector.json');
{
  const s = vector.summary;
  // The quadrature behind the stroke lengths converged; if a later edit breaks
  // that, the lengths are not measurements and the prose must not quote them.
  if (vector.convergence.relativeDrift > 0.05) {
    throw new Error(
      `vector.json: the arc-length quadrature drifted ${pc(vector.convergence.relativeDrift)}% ` +
        `over the last refinement. Re-run tools/exp/vector.mjs.`
    );
  }
  macro('vecZoomLo', vector.zoomRange[0]);
  macro('vecZoomHi', vector.zoomRange[1]);
  macro('vecScenes', 'five');
  macro('vecSettings', s.legibleSettings);
  macro('vecMembersFloor', th(s.membersAtZoomFloor));
  macro('vecInkFloor', th(s.inkPxAtZoomFloor));
  macro('vecSamples', vector.samplesPerPixel);
  // Below one member to a pixel a path renderer can still see what it draws.
  macro('vecQuietContrast', pc(s.belowOnePerPixel.maxContrastLost));
  macro('vecQuietInk', pc(Math.abs(s.belowOnePerPixel.maxInkLost)));
  // At and above two, it cannot.
  macro('vecCrowdedSettings', s.twoAndUp.settings);
  macro('vecCrowdedMedian', pc(s.twoAndUp.medianContrastLost));
  macro('vecWorstContrast', pc(s.maxContrastLost));
  macro('vecWorstContrastRaw', pc(s.maxContrastLostUnblurred));
  macro('vecWorstInk', pc(s.maxInkLost));
  macro('vecWorstPixel', r(s.maxPixelError, 2));
  // The figure's own setting: the scene at its own spacing, at the zoom floor.
  const f = vector.figure;
  macro('vecFigMembers', r(f.membersPerPixel, 1));
  macro('vecFigInk', pc(f.inkLost));
  macro('vecFigContrast', pc(f.contrastLost));
  macro('vecFigAmp', f.amplification);
  console.log(
    `vector: at zoom ${vector.zoomRange[0]} up to ${th(s.membersAtZoomFloor)} members; ` +
      `\`over\` keeps the ink to ${pc(s.maxInkLost)}% but loses a median ` +
      `${pc(s.twoAndUp.medianContrastLost)}% of the fringe contrast past two members a pixel`
  );
}

section('data/contour.json : moire as a contouring primitive');
const contour = load('contour.json');
{
  const means = contour.fields.map((f) => f.meanOffsetPx);
  // The prose says "all six", which is the Studio's Field menu minus `none`. If a
  // seventh field ships, the sentence is wrong: fail rather than mislead.
  if (contour.fields.length !== 6) {
    throw new Error(`contour.json has ${contour.fields.length} fields; \u00a79 says six`);
  }
  macro('contourCarrier', contour.carrierPitch);
  macro('contourDetune', contour.control.detune);
  macro('contourCtlGap', r(contour.control.fringeSpacingPx, 0));
  macro('contourFloor', r(contour.control.meanOffsetPx, 2));
  macro('contourFloorP', r(contour.control.p95OffsetPx, 2));
  macro('contourBestErr', r(Math.min(...means), 2));
  macro('contourWorstErr', r(Math.max(...means), 2));
  // How many presets are at the estimator's own floor, within a rounding step of
  // the two decimals the prose quotes. The abstract counts these.
  const atFloor = means.filter((m) => m <= contour.control.meanOffsetPx + 0.05);
  macro('contourAtFloor', ['zero', 'one', 'two', 'three', 'four', 'five', 'six'][atFloor.length]);
  macro('contourAtFloorErr', r(Math.max(...atFloor), 2));
  macro('contourFieldCount', ['zero', 'one', 'two', 'three', 'four', 'five', 'six'][contour.fields.length]);
  macro('contourWorstP', r(Math.max(...contour.fields.map((f) => f.p95OffsetPx)), 2));
  macro('contourProbes', contour.fields.reduce((a, f) => a + f.probes, 0).toLocaleString('en-US').replace(/,/g, '{,}'));
  macro('contourFinest', r(Math.min(...contour.fields.map((f) => f.finestIntervalPx)), 2));
  const dipole = contour.fields.find((f) => f.name === 'dipole');
  if (!dipole) throw new Error('contour.json has no dipole field');
  macro('contourDipoleResolved', pc(dipole.resolvedFrac, 0));
  macro('contourDipoleFinest', r(dipole.finestIntervalPx, 2));
  console.log(
    `contour: floor ${r(contour.control.meanOffsetPx, 2)}px, fields ` +
      `${r(Math.min(...means), 2)}-${r(Math.max(...means), 2)}px mean`
  );

  // The settings table for the appendix. Reading it out of the same JSON the
  // measurement wrote is the only way the appendix can be trusted to describe the
  // panels the figure actually shows.
  const label = Object.fromEntries(FIELD_PRESETS.map((p) => [p.id, p.label]));
  const rows = contour.fields.map(
    (f) =>
      `\\textsc{${label[f.field].toLowerCase()}} & ${f.amount} & ${f.extent} & ` +
      `${r(f.interval, 3)} & ${r(f.finestIntervalPx, 1)} & ${pc(f.resolvedFrac, 0)}\\% & ` +
      `${r(f.meanOffsetPx, 2)} / ${r(f.p95OffsetPx, 2)} \\\\`
  );
  writeFileSync(
    new URL('tab-fields.tex', PAPER),
    `% GENERATED by paper/tools/numbers.mjs
\\begin{center}\\footnotesize
\\begin{tabular}{@{}lrrrrrr@{}}
  \\toprule
  Field & $a$ & Extent & $c=1/a$ & Finest & Resolved & Error mean / p95 \\\\
  \\midrule
  ${rows.join('\n  ')}
  \\bottomrule
\\end{tabular}
\\end{center}
`
  );

  // The presets, as the text a user would have typed. Generated from the same
  // constant the editor's preset menu reads, so the paper cannot print an
  // expression the tool does not offer.
  const tt = (s) =>
    s
      .replace(/\\/g, '\\textbackslash{}')
      .replace(/\^/g, '\\textasciicircum{}')
      .replace(/([&%$#_])/g, '\\$1')
      // Break opportunities, so a long sum can wrap where a reader would break it.
      .replace(/ ([+-]) /g, ' $1 \\allowbreak ');
  writeFileSync(
    new URL('tab-exprs.tex', PAPER),
    `% GENERATED by paper/tools/numbers.mjs
\\begin{table}[t]
  \\centering
  \\small
  \\caption{The presets the field editor starts from, as the text a user types.
  Nothing here is privileged: each is parsed, compiled and unrolled down the same
  path any typed expression takes, and each is numerically the hand-written field
  it replaced rather than a lookalike.}
  \\label{tab:exprs}
  \\begin{tabular}{@{}lp{0.66\\linewidth}@{}}
    \\toprule
    Preset & Expression \\\\
    \\midrule
${FIELD_PRESETS.map(
  (p) => `    \\textsc{${p.id}} & {\\ttfamily\\scriptsize ${tt(p.source)}} \\\\`
).join('\n')}
    \\bottomrule
  \\end{tabular}
\\end{table}
`
  );
}

// ----------------------------------------------------- selection (convergents)
section('data/convergents.json : which beat wins is best approximation');
{
  const conv = load('convergents.json');
  const s = conv.summary;
  macro('selRatios', s.oneD.ratiosChecked);
  macro('selRecordsMatch', s.oneD.recordsMatchConvergents);
  if (s.oneD.mismatches !== 0) {
    throw new Error('convergents.json reports 1D mismatches; the prose claims none');
  }
  macro('selTrials', th(s.twoD.trials));
  macro('selCapMiss', s.twoD.fringeMissedByCap);
  macro('selCapMissPct', pc(s.twoD.fringeMissedByCap / s.twoD.trials, 0));
  macro('selShipMiss', s.twoD.fringeMissedByShaderScan);
  macro('selShipAgree', th(s.twoD.shaderScanMatchesBruteForce));
  macro('selShipAgreePct', pc(s.twoD.shaderScanMatchesBruteForce / s.twoD.trials, 1));
  macro('selTruthOrder', s.twoD.truthBudget);
  console.log(
    `selection: cap misses ${s.twoD.fringeMissedByCap}/${s.twoD.trials}, ` +
      `shipped scan misses ${s.twoD.fringeMissedByShaderScan}`
  );
}

// ------------------------------------------------------------------- defects
section('data/defects.json : fringe endings count the enclosed charge');
{
  const def = load('defects.json');
  const gated = def.probes.filter((p) => p.expect !== null);
  const failed = def.probes.filter((p) => !p.pass);
  if (failed.length) {
    throw new Error(`defects.json has ${failed.length} failing probes; the prose claims none`);
  }
  macro('defProbes', gated.length);
  macro('defChargeMax', Math.max(...gated.map((p) => Math.abs(p.expect ?? 0))));
  const worstCore = Math.max(...def.core.map((c) => c.relError));
  macro('defCoreWorst', worstCore < 1e-4 ? '10^{-4}' : r(worstCore, 4));
  console.log(`defects: ${gated.length} probes exact, core law within ${worstCore}`);
}

section('data/foldlaw.json : the fold law, gated');
{
  const fold = load('foldlaw.json');
  const failed = fold.gates.filter((g) => !g.pass);
  if (failed.length) {
    throw new Error(`foldlaw.json has ${failed.length} failing gates; the prose claims none`);
  }
  // Worst relative onset error, rotation cases (gauge radius) and Mach cases
  // (onset index) together.
  const errs = fold.t1
    .map((c) => Math.abs(c.measured.rho - c.rhoStar) / c.rhoStar)
    .concat(fold.t2.map((c) => Math.abs(c.measured - c.nStar) / c.nStar));
  macro('foldWorstOnsetPct', r(Math.max(...errs) * 100, 1));
  macro('foldBranchCounts', fold.t4.map((c) => c.crossings).join(', '));
  const birth = fold.gates.filter((g) => g.name.startsWith('crossings born'));
  const deep = fold.gates.filter((g) => g.name.startsWith('deep crossings'));
  macro('foldBirthWorst', r(Math.max(...birth.map((g) => g.worldUnits)), 2));
  macro('foldDeepGaps', r(Math.max(...deep.map((g) => g.gaps)), 1));
  console.log(`foldlaw: worst onset ${r(Math.max(...errs) * 100, 2)}%`);
}

// ------------------------------------------------- paper 2: the gated predictions
// Each script writes a `gates` record; a failing gate stops the build here,
// so the prose can only ever quote a number its experiment stands behind.
/** One significant figure in scientific notation, for LaTeX math. */
const sci = (v) => {
  if (v === 0) return '0';
  const e = Math.floor(Math.log10(Math.abs(v)));
  const m = Math.round(v / 10 ** e);
  return m === 1 ? `10^{${e}}` : `${m}\\times 10^{${e}}`;
};

section('data/dutynull.json : station nulls at rational coarse duty');
{
  const d = load('dutynull.json');
  if (!d.gates.nullDepth || !d.gates.alive) {
    throw new Error('dutynull.json has a failing gate; the prose claims none');
  }
  const depth = (pair, duty) => d.nulls.find((n) => n.pair === pair && Math.abs(n.duty - duty) < 1e-9).depth;
  macro('dutyNullPeriod', Math.round(d.two.period));
  macro('dutyNullDepthTwo', th(depth('2:1', 0.5)));
  macro('dutyNullDepthThreeLow', th(depth('3:1', 1 / 3)));
  macro('dutyNullDepthThreeHigh', th(depth('3:1', 2 / 3)));
  // How far the soft-stroke amplitude sits from the hard-ink law away from
  // the nulls, as a percentage.
  const off = d.two.rows
    .concat(d.three.rows)
    .filter((r) => r.predicted > 0.01)
    .map((r) => Math.abs(r.station - r.predicted) / r.predicted);
  macro('dutyNullLawPct', pc(Math.max(...off), 1));
  console.log(`dutynull: 2:1 null ${depth('2:1', 0.5).toFixed(0)}x, 3:1 nulls ${depth('3:1', 1 / 3).toFixed(0)}x / ${depth('3:1', 2 / 3).toFixed(0)}x`);
}

section('data/exposure.json : temporal selection');
{
  const e = load('exposure.json');
  if (!e.gates.selectivity || !e.gates.faithful) {
    throw new Error('exposure.json has a failing gate; the prose claims none');
  }
  macro('exposureSelectivity', th(e.selectivity));
  macro('exposureFaithfulPct', r(e.faithful * 100, 2));
  macro('exposureStationPeriod', Math.round(e.period));
  console.log(`exposure: selectivity ${e.selectivity.toFixed(0)}x, faithful to ${(e.faithful * 100).toFixed(2)}%`);
}

section('data/observer.json : the observer theorem');
{
  const o = load('observer.json');
  const failed = o.gates.filter((g) => !g.ok);
  if (failed.length) {
    throw new Error(`observer.json has ${failed.length} failing gates; the prose claims none`);
  }
  const flat = o.multiplier.filter((m) => m.c === 0);
  const curved = o.multiplier.filter((m) => m.c > 0 && m.err > 1e-6);
  macro('obsMultiplierErr', sci(Math.max(...flat.map((m) => m.err))));
  macro('obsRemainderResidual', sci(Math.max(...curved.map((m) => m.errCorrected / m.err))));
  macro('obsAdditiveBeat', sci(o.visibility.beat['additive, linear observer']));
  macro('obsPrintedBeat', r(o.visibility.beat['multiplicative, linear observer'], 3));
  macro('obsSquaringBeat', r(o.visibility.beat['additive, squaring observer'], 3));
  macro('obsSaturatingBeat', r(o.visibility.beat['additive, saturating observer'], 3));
  const soft = o.dutyNull.filter((d) => d.aa > 0);
  macro('obsReopenRamps', soft.map((d) => r(d.aa, 2)).join(', '));
  macro('obsReopenAmps', soft.map((d) => sci(d.squared)).join(', '));
  macro('obsHardNull', sci(Math.max(o.dutyNull[0].linear, o.dutyNull[0].squared)));
  console.log(`observer: ${o.gates.length} gates pass; multiplier exact to ${Math.max(...flat.map((m) => m.err)).toExponential(1)}`);
}

section('data/exactsweep.json : the exact sweep, certified');
{
  const x = load('exactsweep.json');
  const failed = x.gates.filter((g) => !g.ok);
  if (failed.length) {
    throw new Error(`exactsweep.json has ${failed.length} failing gates; the prose claims none`);
  }
  macro('exactScenes', x.scenes);
  macro('exactTruthTaps', th(x.truthTaps));
  macro('exactWorstErr', sci(x.worst.exact3));
  macro('exactWorstGrayFrac', Math.round(1 / (x.worst.exact3 * 255)));
  macro('exactGaussFourErr', sci(x.worst.exact4));
  macro('exactGpuErr', sci(x.worst.gpuVsCpu));
  macro('exactTapsWorst', r(x.worst.taps24, 2));
  macro('exactTapsFiftyTwoWorst', r(x.worst.taps52, 3));
  macro('exactOverTaps', th(x.worst.taps24 / x.worst.exact3));
  // The square-law observer's chain: squaring doubles the integrand's degree
  // past what Gauss-3 integrates exactly, so it carries its own receipt.
  macro('exactSquareErr', sci(x.worst.square3));
  macro('exactSquareGpuErr', sci(x.worst.gpuSquare));
  console.log(`exactsweep: ${x.scenes} scenes, chain within ${x.worst.exact3.toExponential(1)}, gpu within ${x.worst.gpuVsCpu.toExponential(1)}`);
}

// ------------------------------------------------- paper 2: the predictions table
// Section 5 of paper 2 is this table and nothing else: every claim with a
// number behind it, the measured value, the gate the build enforces, and the
// script that owns it. Generated here so a row cannot outlive its experiment.
{
  const d = load('dutynull.json');
  const e = load('exposure.json');
  const o = load('observer.json');
  const x = load('exactsweep.json');
  const fold = load('foldlaw.json');
  const def = load('defects.json');
  const conv = load('convergents.json');
  const depth = (pair, duty) => d.nulls.find((n) => n.pair === pair && Math.abs(n.duty - duty) < 1e-9).depth;
  const foldErrs = fold.t1
    .map((c) => Math.abs(c.measured.rho - c.rhoStar) / c.rhoStar)
    .concat(fold.t2.map((c) => Math.abs(c.measured - c.nStar) / c.nStar));
  const rows = [
    ['Duty null: the $2{:}1$ station at coarse duty $1/2$', `$${th(depth('2:1', 0.5))}\\times$ below its neighbours`, '$>10\\times$', 'dutynull.mjs'],
    ['Duty nulls: the $3{:}1$ station at $1/3$ and $2/3$', `$${th(depth('3:1', 1 / 3))}\\times$, $${th(depth('3:1', 2 / 3))}\\times$`, '$>10\\times$ each', 'dutynull.mjs'],
    ['Temporal selection: rates $(1,2)$ keep the station, $(1,1)$ and $(2,1)$ wash it', `$${th(e.selectivity)}\\times$; kept to ${r(e.faithful * 100, 2)}\\% of the still`, '$>30\\times$; $<2\\%$', 'exposure.mjs'],
    ['Exact sweep: Gauss-3 chain against a 65\\,536-tap truth', `$${sci(x.worst.exact3)}$ over ${x.scenes} scenes`, '$<2\\times10^{-3}$', 'exactsweep.mjs'],
    ['Exact sweep: every corner named (Gauss-4)', `$${sci(x.worst.exact4)}$`, '$<10^{-5}$', 'exactsweep.mjs'],
    ['Exact sweep: the shipped shader against its double-precision twin', `$${sci(x.worst.gpuVsCpu)}$`, '$<10^{-4}$', 'exactsweep.mjs'],
    ['Exact sweep: the square-law observer\'s chain against the squared truth, and its shader against the twin', `$${sci(x.worst.square3)}$; $${sci(x.worst.gpuSquare)}$`, '$<2\\times10^{-3}$; $<10^{-4}$', 'exactsweep.mjs'],
    ['Observer: a window is the torus multiplier', `$${sci(Math.max(...o.multiplier.filter((m) => m.c === 0).map((m) => m.err)))}$`, '$<5\\times10^{-5}$', 'observer.mjs'],
    ['Observer: the curvature remainder is the multiplier\'s second derivative', `residual $${sci(Math.max(...o.multiplier.filter((m) => m.c > 0 && m.err > 1e-6).map((m) => m.errCorrected / m.err)))}$ of the remainder`, '$<0.1$', 'observer.mjs'],
    ['Observer: additive light has no linear beat', `$${sci(o.visibility.beat['additive, linear observer'])}$`, '$<10^{-10}$', 'observer.mjs'],
    ['Observer: a squaring front end mints it at $\\hat g_1(1)\\hat g_2(1)/2$', `${r(o.visibility.beat['additive, squaring observer'], 4)} vs ${r(o.visibility.product / 2, 4)}`, 'rel.\\ $<10^{-6}$', 'observer.mjs'],
    ['Observer: hard ink is observer-proof', `$${sci(Math.max(o.dutyNull[0].linear, o.dutyNull[0].squared))}$`, '$<10^{-12}$', 'observer.mjs'],
    ['Observer: soft ink reopens the null under squaring, linearly in the ramp', `$${o.dutyNull.filter((q) => q.aa > 0).map((q) => sci(q.squared)).join('$, $')}$`, 'monotone, $>10^{-4}$', 'observer.mjs'],
    ['Fold law: onset radii of rotating gauges and Mach drifts', `within ${r(Math.max(...foldErrs) * 100, 1)}\\%`, 'every onset gate', 'foldlaw.mjs'],
    ['Fold law: crossings are born on the caustic', `within ${r(Math.max(...fold.gates.filter((g) => g.name.startsWith('crossings born')).map((g) => g.worldUnits)), 2)} world units`, 'every birth gate', 'foldlaw.mjs'],
    ['Untwist: rational twists split into convex classes', 'exact at $\\theta=4\\pi/7$', 'splits exact', 'foldlaw.mjs'],
    ['Branch counts grow linearly in radius', fold.t4.map((c) => c.crossings).join(', '), 'as predicted', 'foldlaw.mjs'],
    ['Defects: fringe endings count the enclosed charge', `${def.probes.filter((p) => p.expect !== null).length} probes exact, charges to ${Math.max(...def.probes.map((p) => Math.abs(p.expect ?? 0)))}`, 'exact', 'defects.mjs'],
    ['Defects: the core radius $2As/\\pi$', `within ${Math.max(...def.core.map((c) => c.relError)) < 1e-4 ? '$10^{-4}$' : r(Math.max(...def.core.map((c) => c.relError)), 4)}`, 'gated', 'defects.mjs'],
    ['Selection: record beats are convergents', `${conv.summary.oneD.recordsMatchConvergents} of ${conv.summary.oneD.recordsMatchConvergents}`, 'no mismatch', 'convergents.mjs'],
    ['Selection: the reduction window names the brute-force winner', `${pc(conv.summary.twoD.shaderScanMatchesBruteForce / conv.summary.twoD.trials, 1)}\\% of ${th(conv.summary.twoD.trials)}`, `misses ${conv.summary.twoD.fringeMissedByShaderScan}`, 'convergents.mjs'],
  ];
  const tex = [
    '% GENERATED by paper/tools/numbers.mjs -- do not edit by hand.',
    '\\begin{tabular}{@{}p{0.36\\linewidth}p{0.25\\linewidth}p{0.16\\linewidth}l@{}}',
    '\\toprule',
    'Claim & Measured & Gate & Script \\\\',
    '\\midrule',
    ...rows.map(([a, b, c, dd]) => `${a} & ${b} & ${c} & \\texttt{${dd}} \\\\`),
    '\\bottomrule',
    '\\end{tabular}',
    '',
  ];
  writeFileSync(new URL('tab-predictions.tex', PAPER), tex.join('\n'));
  console.log(`predictions table: ${rows.length} rows`);
}

writeFileSync(new URL('numbers.tex', PAPER), out.join('\n') + '\n');
console.log(`\nwrote numbers.tex (${out.filter((l) => l.startsWith('\\newcommand')).length} macros)`);
